[custom]
;当前配置二改于：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/config/ACL4SSR_Online_NoReject.ini
;GH-CDN: https://cdn.jsdelivr.net/gh/adiovo/clash-rules/sub-config/Adi_Online_NoReject.ini

;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持

ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/LocalAreaNetwork.list,10800
ruleset=📢 谷歌FCM,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/GoogleFCM.list,10800
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/GoogleCN.list,10800
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/SteamCN.list,10800
ruleset=Ⓜ️ 微软服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Microsoft.list,10800
ruleset=Ⓜ️ 微软Bing,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Bing.list,10800
ruleset=Ⓜ️ 微软云盘,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/OneDrive.list,10800
ruleset=🍎 苹果服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Apple.list,10800
ruleset=📲 电报信息,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Telegram.list,10800
ruleset=🌍 国外媒体,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ProxyMedia.list,10800
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ProxyLite.list,10800
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ChinaDomain.list,10800
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ChinaCompanyIp.list,10800

;增强直连
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt,10800
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt,10800
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/LM-Firefly/Rules/Special/NTP-Service.list,10800
;增强代理分流
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt,10800
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt,10800
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt,10800
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/LM-Firefly/Rules/PROXY.list,10800
;TODO：补充下载服务分流相关

;AI分流
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/AI.list,10800
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/OpenAi.list,10800

;自定义规则集
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/adiovo/clash-rules/rules-providers/private/proxy.yaml,43200
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/adiovo/clash-rules/rules-providers/private/direct.yaml,43200
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://connectivitycheck.gstatic.com/generate_204`180,20,60
custom_proxy_group=🔯 故障转移`fallback`.*`https://connectivitycheck.gstatic.com/generate_204`180,20,60
custom_proxy_group=🔮 负载均衡`load-balance`.*`https://connectivitycheck.gstatic.com/generate_204`180,20,60
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*

enable_rule_generator=true
overwrite_original_rules=true
